name: Update readme

on:
    schedule:
        - cron: "0 3,6,9,12,15,18,21 * * *"
    workflow_dispatch:

jobs:
    readme:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: 14
            - run: npm install

            - name: Generate readme
              env:
                  AIR_API_KEY: ${{ secrets.AIR_API_KEY }}
              run: node build-svg.js

            - name: Commit changes
              uses: EndBug/add-and-commit@v4
              with:
                  author_name: sami
                  author_email: ksm5@torder.com
                  message: "Auto updating my readme"
                  add: "chat.svg"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
